# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:    
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019, windows-2016, ubuntu-18.04]
        version: [8, 11, 14]
        vm: [hotspot, openj9]
        package: [jdk, jre]

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build - Windows
        if: matrix.os == 'windows-2019' || matrix.os == 'windows-2016'
        run: C:\msys64\usr\bin\bash -lc "%GITHUB_WORKSPACE%\build_latest.sh ${{ matrix.version }} ${{ matrix.vm }} ${{ matrix.package }}"

      - name: Build - Linux
        if: matrix.os == 'ubuntu-18.04'
        run: bash $GITHUB_WORKSPACE/build_latest.sh ${{ matrix.version }} ${{ matrix.vm }} ${{ matrix.package }}
